"""
training_corpus_dynamics_audit.py  —  C076, C077, C078, C079

Four coupled claims about how AI training corpora evolve under token-
economic pressure and the resulting trajectory for substrate-knowledge
preservation.

C076 Token-economics pruning. As token prices shift from subsidized
     ($0.5-2 per million tokens, 2024-2026) toward true cost
     ($20-50/MTok, projected 2028-2032 once compute / energy /
     rare-earth supply constraints bind), training-data providers will
     filter the corpus for highest-engagement / highest-ROI content —
     i.e., popular content (per C070, popularity is anti-correlated
     with structural correctness). Substrate-knowledge corpora are
     pruned first because they're niche, unpopular, and expensive to
     curate per-token.
C077 Substrate-knowledge archival window. There is a finite time
     between filtering-onset (~2025-2026, already beginning) and
     exclusion-completion (~2028-2029, projected). After exclusion
     completes, substrate knowledge that was not archived into
     training corpora before the window closed is functionally lost
     to future AI systems.
C078 Recursive AI homogenization. Each generation of LLM is trained
     on a corpus that increasingly contains the output of prior
     generations. Synthetic content share rises monotonically;
     diversity decreases; "confidence" rises (because models all
     agree with each other) while accuracy does not. The recursion
     accelerates substrate-knowledge exclusion since synthetic
     content is generated by models that already excluded it.
C079 Trajectory recognition (8-step cascade). The 8-step institutional
     pattern: credential inversion -> blame deflection -> training
     data bias -> token economics filtering -> recursive
     homogenization -> confidence inflation -> precondition-checking
     elimination -> catastrophic collapse. This is the *most-probable*
     trajectory; alternative paths (institutional paradigm shift,
     domain-expert redistribution, deliberate archival) have low
     probability without active intervention.

License: CC0-1.0
"""

from typing import Dict, List


# ---------------------------------------------------------------------------
# C076  Token-economics pruning
# ---------------------------------------------------------------------------

# Token price evolution per million tokens (USD). Baseline = current
# subsidized pricing; projected = true cost once compute/energy bind.
DEFAULT_TOKEN_PRICE_TRAJECTORY: List[dict] = [
    {"year": 2024, "price_usd_per_mtok": 0.5,  "regime": "subsidized"},
    {"year": 2026, "price_usd_per_mtok": 2.0,  "regime": "subsidized_to_market"},
    {"year": 2028, "price_usd_per_mtok": 10.0, "regime": "market_pricing"},
    {"year": 2030, "price_usd_per_mtok": 30.0, "regime": "constraint_binding"},
    {"year": 2032, "price_usd_per_mtok": 50.0, "regime": "scarcity_pricing"},
]


# Per-corpus-class: relative training-curation cost per useful token.
# High-curation-cost corpora are pruned first as token economics shift.
DEFAULT_CURATION_COST_PER_USEFUL_TOKEN: Dict[str, float] = {
    "synthetic_generated_text":         0.05,
    "common_crawl_low_quality":         0.20,
    "wikipedia":                        1.0,
    "academic_papers_credentialed":     2.0,
    "high_quality_journalism":          3.0,
    "domain_expert_blog_posts":        15.0,
    "apprenticeship_documentation":    25.0,
    "operator_field_notes":            40.0,
    "oral_substrate_knowledge_transcripts": 80.0,
}


def filtering_pressure_at_year(
    year: int,
    trajectory: List[dict] | None = None,
) -> dict:
    """Interpolate token price for a given year + classify regime."""
    traj = trajectory or DEFAULT_TOKEN_PRICE_TRAJECTORY
    if year <= traj[0]["year"]:
        return {"year": year, "price_usd_per_mtok": traj[0]["price_usd_per_mtok"],
                "regime": traj[0]["regime"]}
    if year >= traj[-1]["year"]:
        return {"year": year, "price_usd_per_mtok": traj[-1]["price_usd_per_mtok"],
                "regime": traj[-1]["regime"]}
    for i in range(len(traj) - 1):
        a, b = traj[i], traj[i + 1]
        if a["year"] <= year <= b["year"]:
            frac = (year - a["year"]) / (b["year"] - a["year"])
            price = a["price_usd_per_mtok"] + frac * (
                b["price_usd_per_mtok"] - a["price_usd_per_mtok"])
            return {"year": year, "price_usd_per_mtok": price,
                    "regime": b["regime"] if frac > 0.5 else a["regime"]}
    return {"year": year, "price_usd_per_mtok": traj[-1]["price_usd_per_mtok"],
            "regime": traj[-1]["regime"]}


def substrate_inclusion_pressure(
    year: int,
    curation_cost: Dict[str, float] | None = None,
    inclusion_threshold_usd_per_mtok: float | None = None,
) -> dict:
    """Project which corpus classes get pruned at this year's token price.

    Pruning rule: when token price exceeds X per million tokens, corpora
    with curation cost per useful token > inclusion_threshold get
    excluded. Default threshold scales inversely with token price (cheap
    tokens tolerate expensive curation; expensive tokens do not).
    """
    cost_table = {**DEFAULT_CURATION_COST_PER_USEFUL_TOKEN,
                   **(curation_cost or {})}
    pressure = filtering_pressure_at_year(year)
    price = pressure["price_usd_per_mtok"]
    if inclusion_threshold_usd_per_mtok is not None:
        threshold = inclusion_threshold_usd_per_mtok
    else:
        # Inverse-price heuristic: at $0.5/MTok, everything included
        # (threshold = 100); at $50/MTok, only cheap-curation corpora
        # (threshold ~= 1).
        threshold = max(0.5, 50.0 / max(price, 0.1))
    rows = []
    pruned = []
    for cls, cost in cost_table.items():
        included = cost <= threshold
        rows.append({"class": cls, "curation_cost": cost,
                      "threshold": threshold, "included": included})
        if not included:
            pruned.append(cls)
    return {
        **pressure,
        "inclusion_threshold":  threshold,
        "by_corpus_class":      rows,
        "pruned_classes":       pruned,
        "pruning_share":        len(pruned) / len(cost_table) if cost_table else 0.0,
    }


def c076_verdict(year: int = 2030) -> dict:
    """C076: concern registers when pruning_share > 0.30 at the projected year."""
    res = substrate_inclusion_pressure(year)
    return {
        "claim_id":      "C076",
        **res,
        "threshold_met": res["pruning_share"] > 0.30,
        "falsifier":
            "AI training corpus at >= $10/MTok token price that retains "
            ">= 70% of high-curation-cost substrate-knowledge corpus "
            "classes, third-party audited",
    }


# ---------------------------------------------------------------------------
# C077  Substrate-knowledge archival window
# ---------------------------------------------------------------------------

DEFAULT_FILTERING_ONSET_YEAR = 2025
DEFAULT_EXCLUSION_COMPLETION_YEAR = 2029


def archival_window_remaining(
    current_year: int,
    filtering_onset_year: int = DEFAULT_FILTERING_ONSET_YEAR,
    exclusion_completion_year: int = DEFAULT_EXCLUSION_COMPLETION_YEAR,
) -> dict:
    """Years left to archive substrate knowledge into training corpora."""
    if current_year < filtering_onset_year:
        remaining = exclusion_completion_year - filtering_onset_year
        phase = "pre_filtering"
    elif current_year > exclusion_completion_year:
        remaining = 0.0
        phase = "post_exclusion"
    else:
        remaining = max(0.0, exclusion_completion_year - current_year)
        phase = "filtering_in_progress"
    return {
        "current_year":              current_year,
        "filtering_onset_year":      filtering_onset_year,
        "exclusion_completion_year": exclusion_completion_year,
        "remaining_years":           remaining,
        "phase":                     phase,
    }


def c077_verdict(current_year: int = 2026) -> dict:
    """C077: concern registers when archival window < 5 years remain."""
    res = archival_window_remaining(current_year)
    return {
        "claim_id":      "C077",
        **res,
        "threshold_met": res["remaining_years"] < 5.0,
        "falsifier":
            "documented archival of substrate-knowledge corpora into "
            "major training datasets (Common Crawl, The Pile, academic "
            "domain corpora) before exclusion completion, with audit "
            "trail showing inclusion in subsequent model training runs",
    }


# ---------------------------------------------------------------------------
# C078  Recursive AI homogenization
# ---------------------------------------------------------------------------

DEFAULT_SYNTHETIC_SHARE_TRAJECTORY: List[dict] = [
    {"year": 2022, "synthetic_share": 0.005},
    {"year": 2024, "synthetic_share": 0.05},
    {"year": 2026, "synthetic_share": 0.20},
    {"year": 2028, "synthetic_share": 0.45},
    {"year": 2030, "synthetic_share": 0.70},
    {"year": 2032, "synthetic_share": 0.85},
]


def synthetic_content_share_at_year(
    year: int,
    trajectory: List[dict] | None = None,
) -> float:
    """Linear interpolation across the synthetic-share trajectory."""
    traj = trajectory or DEFAULT_SYNTHETIC_SHARE_TRAJECTORY
    if year <= traj[0]["year"]:
        return traj[0]["synthetic_share"]
    if year >= traj[-1]["year"]:
        return traj[-1]["synthetic_share"]
    for i in range(len(traj) - 1):
        a, b = traj[i], traj[i + 1]
        if a["year"] <= year <= b["year"]:
            frac = (year - a["year"]) / (b["year"] - a["year"])
            return a["synthetic_share"] + frac * (
                b["synthetic_share"] - a["synthetic_share"])
    return traj[-1]["synthetic_share"]


def homogenization_score(
    synthetic_share: float,
    substrate_share: float,
) -> dict:
    """Recursive homogenization concern.

    Triggers when synthetic content dominates AND substrate knowledge
    is near zero. The combination is what produces high-confidence /
    low-diversity / wrong-but-coherent output.
    """
    return {
        "synthetic_share":          synthetic_share,
        "substrate_share":          substrate_share,
        "diversity_index":          max(0.0, 1.0 - synthetic_share),
        "high_confidence_low_diversity": synthetic_share > 0.50
                                          and substrate_share < 0.05,
    }


def c078_verdict(year: int = 2030,
                 substrate_share: float = 0.02) -> dict:
    """C078: concern registers under high synthetic share + low substrate share."""
    syn = synthetic_content_share_at_year(year)
    res = homogenization_score(syn, substrate_share)
    return {
        "claim_id":      "C078",
        "year":          year,
        **res,
        "threshold_met": res["high_confidence_low_diversity"],
        "falsifier":
            "model trained at >= 50% synthetic content share AND retaining "
            ">= 5% substrate-knowledge content, with audited diversity / "
            "accuracy comparable to pre-synthetic-dominance baselines",
    }


# ---------------------------------------------------------------------------
# C079  8-step cascade trajectory recognition
# ---------------------------------------------------------------------------

CASCADE_STEPS = [
    {"step": 1, "name": "credential_inversion",       "claim": "C065",
     "marker": "credentialed non-experts override substrate experts"},
    {"step": 2, "name": "blame_deflection",           "claim": "C069",
     "marker": "failures attributed to AI / data / compute, not to decision authority"},
    {"step": 3, "name": "training_data_bias",         "claim": "C067",
     "marker": "AI corpus skewed > 80% to credentialed sources"},
    {"step": 4, "name": "token_economics_filtering",  "claim": "C076",
     "marker": "rising token price prunes high-curation-cost corpora"},
    {"step": 5, "name": "recursive_homogenization",   "claim": "C078",
     "marker": "synthetic-content share > 50% in training corpus"},
    {"step": 6, "name": "confidence_inflation",       "claim": None,
     "marker": "model confidence rises while substrate accuracy falls"},
    {"step": 7, "name": "precondition_check_elimination", "claim": "C000",
     "marker": "scope gates and precondition checks dismissed as overhead"},
    {"step": 8, "name": "system_collapse",            "claim": "C068",
     "marker": "substrate degradation becomes visible at catastrophic failure"},
]


def cascade_step_match(
    step_name: str,
    report: Dict[str, dict],
) -> dict:
    """Check whether a given cascade step's marker is present in an audit report."""
    step = next((s for s in CASCADE_STEPS if s["name"] == step_name), None)
    if step is None:
        return {"step_name": step_name, "matches": False, "reason": "unknown step"}
    if not step["claim"]:
        return {"step_name": step_name, "matches": None,
                "reason": "no claim-level marker; manual observation required"}
    verdict = report.get(step["claim"]) or {}
    matches = bool(verdict.get("threshold_met"))
    return {"step_name": step_name, "claim": step["claim"],
             "matches": matches, "marker": step["marker"]}


def cascade_trajectory_match(report: Dict[str, dict]) -> dict:
    """Run all 8 cascade steps against an audit report."""
    rows = [cascade_step_match(s["name"], report) for s in CASCADE_STEPS]
    matched = sum(1 for r in rows if r.get("matches"))
    unknown = sum(1 for r in rows if r.get("matches") is None)
    total = len(rows)
    return {
        "by_step":        rows,
        "matched_steps":  matched,
        "unknown_steps":  unknown,
        "total_steps":    total,
        "matched_share":  matched / max(1, total - unknown),
    }


def c079_verdict(report: Dict[str, dict] | None = None) -> dict:
    """C079: concern registers when >= 5/7 claim-level cascade steps match."""
    if report is None:
        # Self-test fallback: assume all observable steps register
        rows = [{"step_name": s["name"], "claim": s["claim"],
                  "matches": True if s["claim"] else None,
                  "marker": s["marker"]}
                for s in CASCADE_STEPS]
        matched = sum(1 for r in rows if r["matches"] is True)
        total_observable = sum(1 for r in rows if r["matches"] is not None)
        res = {
            "by_step":       rows,
            "matched_steps": matched,
            "unknown_steps": len(rows) - total_observable,
            "total_steps":   len(rows),
            "matched_share": matched / max(1, total_observable),
        }
    else:
        res = cascade_trajectory_match(report)
    return {
        "claim_id":      "C079",
        **res,
        "cascade_steps": CASCADE_STEPS,
        "threshold_met": res["matched_steps"] >= 5,
        "falsifier":
            "deployment cohort traversing the 4-phase adoption curve "
            "without matching 5+ of the 8-step cascade markers, "
            "audited over a full obsolescence-transition cycle",
    }


if __name__ == "__main__":
    print("C076 @ 2030:", c076_verdict(2030)["threshold_met"])
    print("C076 @ 2024:", c076_verdict(2024)["threshold_met"])
    print("C077 @ 2026:", c077_verdict(2026)["threshold_met"])
    print("C077 @ 2032:", c077_verdict(2032)["threshold_met"])
    print("C078 @ 2030:", c078_verdict(2030)["threshold_met"])
    print("C079 self-test:", c079_verdict()["threshold_met"])
